### ISSUE TITLE
The AOI is a filled blue feature

### ISSUE THREAD

**Issue by 12rambau** [sepal-contrib/planet_active_fires_explorer#44]
As the AOI is filled, there is a light blue filter on anything displayed in the map.

With the AOI selected: 
![image](https://user-images.githubusercontent.com/12596392/174008983-cdfbb6b6-85a5-4eb4-9988-87ea115b7435.png)

without:

![image](https://user-images.githubusercontent.com/12596392/174009057-786b49a2-93f3-4914-9f31-83b3c914ad15.png)

**Comment by dfguerrerom** [comment]
The blue overlay is only happening when using drawing tools. Fixed with f4722b1102f84bc441226dbf194f2798cdcfcacb.
