### ISSUE TITLE
Still cannot zoom on the map and also getting error when trying to download alerts

### ISSUE THREAD

**Issue by eriklindquist** [sepal-contrib/planet_active_fires_explorer#52]
I receive this error:
'DataFrame' object has no attribute 'longitude'
when trying to download any alerts (recent) for Mexico

**Comment by dfguerrerom** [comment]
I'm not sure yet, but SEPAL map is also having this issue when `drawing mode: polygon` is selected, this app by default loads "draw" mode as AOI selection method, we could get more clues if the problem there is sorted.
